### ISSUE TITLE
limitation idle

### ISSUE THREAD

**Issue by pergolafabio** [dnguyen800/Spotify-Playlist-Card#8]
Hi, i have  a receiver with spotify connect, so i also have the "idle" issue

seems 105.x release is using a new kind of spotify integration
will this help the idle issue?

**Comment by pergolafabio** [comment]
according to below, it now detects : Discovery of an active Spotify Connect on the network

https://github.com/home-assistant/home-assistant/pull/30717

**Comment by dnguyen800** [comment]
i'll look into it when .105 releases.

**Comment by pergolafabio** [comment]
ok, thnx in advance

at the moment i am using your playlist card, when its idle, i just fire this script before
seems thats enough to make it not "idle"

isnt it an option in your platlist to check the state? if idle, then fire below ?


```
spotify_on:
  sequence:
  - service: media_player.select_source
    data_template:
      entity_id: media_player.spotify
      source: Denon AVR-X4000
```
